services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: todo-app-image
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - ./server/database:/app/database