services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client-image
    container_name: client
    ports:
      - "3000:80"
    volumes:
      - ./client:/usr/share/nginx/html

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: server-image
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
  
  sqlite-web:
    build:
      context: ./sqlite-web
      dockerfile: Dockerfile
    image: sqlite-web-image
    container_name: sqlite-web
    ports:
      - "8081:8080"
    volumes:
      - ./server/database:/app/database